# Generated by Django 5.1.15 on 2026-04-05 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedTargetRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(help_text='CIDR notation, e.g. 192.168.1.0/24 or 10.0.0.0/8', max_length=43)),
                ('description', models.TextField(blank=True, help_text='Purpose of this target range')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approved Target Range',
                'verbose_name_plural': 'Approved Target Ranges',
                'db_table': 'approved_target_ranges',
            },
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly scan name', max_length=200)),
                ('target', models.CharField(help_text='Target IP or CIDR range', max_length=500)),
                ('scan_config', models.CharField(default='full_and_fast', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Scan Completed'), ('analyzing', 'AI Analyzing'), ('analyzed', 'Analysis Complete'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Scan progress 0-100')),
                ('gvm_task_id', models.CharField(blank=True, max_length=100)),
                ('gvm_target_id', models.CharField(blank=True, max_length=100)),
                ('gvm_report_id', models.CharField(blank=True, max_length=100)),
                ('raw_report_xml', models.TextField(blank=True, help_text='Raw OpenVAS XML report')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_tasks', to='compliance.framework')),
            ],
            options={
                'verbose_name': 'Scan Task',
                'verbose_name_plural': 'Scan Tasks',
                'db_table': 'scan_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
