# Generated by Django 5.1.15 on 2026-04-05 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compliance Framework',
                'verbose_name_plural': 'Compliance Frameworks',
                'db_table': 'frameworks',
                'ordering': ['name'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='FrameworkControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(help_text='Control identifier, e.g. A.5.1 or Art.32', max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Full control requirement text')),
                ('category', models.CharField(help_text='Control category, e.g. Access Control, Cryptography', max_length=100)),
                ('keywords', models.JSONField(default=list, help_text='Keywords for matching vulnerabilities to this control')),
                ('guidance', models.TextField(blank=True, help_text='Implementation guidance')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='compliance.framework')),
            ],
            options={
                'verbose_name': 'Framework Control',
                'verbose_name_plural': 'Framework Controls',
                'db_table': 'framework_controls',
                'ordering': ['framework', 'control_id'],
                'unique_together': {('framework', 'control_id')},
            },
        ),
    ]
