# Generated by Django 5.1.15 on 2026-04-05 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('executive', 'Executive Compliance Report'), ('technical', 'Technical Remediation Plan')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='reports/%Y/%m/')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('compliance_score', models.FloatField(blank=True, help_text='Overall compliance score as percentage (0-100)', null=True)),
                ('findings_count', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('scan_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scanner.scantask')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
