# Generated by Django 5.1.15 on 2026-04-05 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vulnerability name / NVT title', max_length=500)),
                ('cve_ids', models.JSONField(default=list, help_text='List of CVE IDs, e.g. ["CVE-2023-1234"]')),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Log', 'Log')], default='Log', max_length=20)),
                ('host', models.CharField(help_text='Target host IP (stored locally, never sent to AI)', max_length=100)),
                ('port', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True, help_text='Suggested fix from the scanner')),
                ('references', models.JSONField(default=list, help_text='URLs and reference links')),
                ('nvt_oid', models.CharField(blank=True, help_text='OpenVAS NVT OID', max_length=100)),
                ('qod', models.IntegerField(blank=True, help_text='Quality of Detection (0-100)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.scantask')),
            ],
            options={
                'verbose_name': 'Technical Finding',
                'verbose_name_plural': 'Technical Findings',
                'db_table': 'technical_findings',
                'ordering': ['-cvss_score', 'severity'],
            },
        ),
        migrations.CreateModel(
            name='AIIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_controls', models.JSONField(default=list, help_text='List of matched control objects from AI analysis')),
                ('overall_risk', models.CharField(help_text='AI-assessed risk level: HIGH, MEDIUM, LOW', max_length=20)),
                ('executive_summary', models.TextField(help_text='Non-technical explanation for auditors')),
                ('technical_remediation', models.TextField(help_text='Step-by-step remediation for engineers')),
                ('pass_fail', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], default='FAIL', max_length=4)),
                ('raw_ai_response', models.JSONField(help_text='Complete raw AI response for audit trail')),
                ('tokens_used', models.IntegerField(default=0, help_text='Total tokens consumed')),
                ('cached', models.BooleanField(default=False, help_text='Whether result came from cache')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('technical_finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_ingestion', to='interceptor.technicalfinding')),
            ],
            options={
                'verbose_name': 'AI Ingestion Record',
                'verbose_name_plural': 'AI Ingestion Records',
                'db_table': 'ai_ingestion',
            },
        ),
    ]
