# Generated by Django 5.1.15 on 2026-04-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interceptor', '0002_remove_aiingestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalfinding',
            name='severity',
            field=models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Log', 'Log')], default='Log', max_length=20),
        ),
    ]
